load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "ifaddrs",
    srcs = ["ifaddrs.c"],
    hdrs = ["ifaddrs.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//utils/logger",
    ],
)
