load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "vector",
    hdrs = ["check.h", "status.h", "vector.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//utils/logger:logger",
    ]
)
